# GUI

cask "docker-desktop"
cask "firefox"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "iina"
cask "keepassxc"
cask "maccy"
cask "mos", args: { no_quarantine: true }
cask "numi"
cask "obsidian"
cask "sublime-text"
cask "the-unarchiver"
cask "ukelele"
cask "visual-studio-code"

# CLI

brew "atuin"
brew "duf"
brew "eza"
brew "fd"
brew "forgit"
brew "fzf"
brew "just"
brew "mas"
tap "netbirdio/tap"
brew "netbirdio/tap/netbird"
brew "oh-my-posh"
brew "rustup"
brew "scc"
brew "starship"
brew "stow"
brew "telnet"
brew "unar"
brew "watchexec"
brew "xh"
brew "zoxide"

# TUI

brew "dua-cli"
brew "helix"
brew "lazydocker"
brew "lazygit"
brew "mactop"
brew "neovim"
brew "tmux"

# WORK

cask "dbeaver-community"
cask "mongodb-compass"
cask "mqtt-explorer"
cask "openvpn-connect"
cask "slack"

brew "cmake"
tap  "fluxcd/tap"
brew "fluxcd/tap/flux"
brew "gnuplot"
brew "helm-docs"
brew "helm"
brew "k3d"
brew "k9s"
brew "kubelogin"
brew "libpq", link: true
brew "logcli"
brew "minikube"
brew "mongosh"
brew "node"
brew "openssl@3"
brew "or-tools"
brew "protobuf"
brew "stern"
brew "tilt"