theme = "rose_pine"

[editor]
line-number = "relative"
color-modes = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
Cmd-s = ":write"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
