[language-server.rust-analyzer.config]
check = { command = "clippy", allTargets = true } 

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }
