name: Darwin Nix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: 1
  NONINTERACTIVE: 1
  NIX_INSTALLER_NO_CONFIRM: true
    
jobs:
  install-on-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
    - name: Test Install
      run: just install
